name: wrfcuenca3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - affine=2.3.0=py_0
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - bokeh=2.0.1=py38h32f6830_0
  - boost-cpp=1.72.0=h8e57a91_0
  - bottleneck=1.3.2=py38h8790de6_1
  - brotlipy=0.7.0=py38h1e0a361_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=hcf35c78_1003
  - cartopy
  - certifi=2020.4.5.1=py38h32f6830_0
  - cffi=1.14.0=py38he30daa8_1
  - cfitsio=3.470=hb60a0a2_2
  - cftime=1.1.3=py38h8790de6_0
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.4.1=py_0
  - cryptography=2.9.2=py38h766eaa4_0
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py38h516909a_0
  - dask=2.16.0=py_0
  - dask-core=2.16.0=py_0
  - descartes=1.1.0=py_4
  - distributed=2.16.0=py38h32f6830_0
  - expat=2.2.9=he1b5a44_2
  - fiona=1.8.13=py38h900e953_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - freexl=1.0.5=h14c3975_1002
  - fsspec=0.7.4=py_0
  - gazar=0.0.4=py_1
  - gdal=3.0.2=py38hbb6b9fb_2
  - geopandas=0.7.0=py_1
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.5.1=hbd99317_7
  - giflib=5.1.7=h516909a_1
  - glib=2.63.1=h3eb4bd4_1
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - heapdict=1.0.1=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=hbfbb72e_1002
  - kealib=1.4.13=hec59c27_0
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.68.0=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=3.0.2=hc7cfd23_2
  - libgfortran-ng
  - libiconv=1.15=h516909a_1006
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.7.1=nompi_h94020b1_102
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libpq=11.5=hd9ab2ff_2
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=h4f6d029_1032
  - libssh2=1.9.0=hab1572f_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=he1b5a44_1001
  - mapkit=1.2.6=py_1
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib-base=3.2.1=py38h2af1d28_0
  - msgpack-python=1.0.0=py38hbf85e49_1
  - munch=2.5.0=py_0
  - ncurses=6.2=he6710b0_1
  - netcdf4=1.5.3=nompi_py38hfee4bf2_101
  - numpy=1.18.4=py38h8854b6b_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_0
  - owslib=0.19.2=py_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.3=py38hcb8c335_1
  - partd=1.1.0=py_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=20.0.2=py38_3
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_2
  - proj=6.2.1=hc80f0dc_0
  - psutil=5.7.0=py38h1e0a361_1
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=py_0
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py38h8790de6_1003
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.4.1=py38h12732c1_1
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.2=hcff3b4d_14
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - rasterio=1.1.2=py38h900e953_0
  - rasterstats=0.14.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=pyh8c360ce_2
  - rtree=0.9.4=py38h08f867b_1
  - scipy=1.4.1=py38h18bccfc_3
  - setuptools=46.4.0=py38_0
  - shapely=1.6.4=py38hec07ddf_1006
  - simplejson=3.17.0=py38h1e0a361_1
  - six=1.15.0=pyh9f0ad1d_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.1.0=py_0
  - sqlalchemy=1.3.17=py38h1e0a361_0
  - sqlite=3.31.1=h62c20be_1
  - tbb=2018.0.5=h2d50403_0
  - tblib=1.6.0=py_0
  - tiledb=1.6.2=hcde45ca_3
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py38h1e0a361_1
  - typing_extensions=3.7.4.2=py_0
  - tzcode=2020a=h516909a_0
  - urllib3=1.25.9=py_0
  - utm=0.5.0=py_0
  - wheel=0.34.2=py38_0
  - wrapt=1.12.1=py38h1e0a361_1
  - wrf-python=1.3.2=py38h7eb8c7e_1
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.4=h516909a_0
  - zict=2.0.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - backcall==0.1.0
    - decorator==4.4.2
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - jedi==0.17.0
    - matplotlib==3.1.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - traitlets==4.3.3
    - wcwidth==0.1.9
    - xarray==0.14.1
    - ray==0.8.5

